# Generated by Django 4.0.4 on 2023-08-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tok', models.CharField(max_length=168)),
                ('file_name', models.CharField(max_length=168)),
                ('platform', models.CharField(max_length=64)),
                ('environ', models.CharField(max_length=64)),
            ],
        ),
    ]
